<a href="https://colab.research.google.com/github/OmamaSajid/deeplearning/blob/main/pytorchbase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
mylist=[1,2,3,4]
mylist
myls=[[1,2,3],[4,5,6]]
myls

[[1, 2, 3], [4, 5, 6]]

In [ ]:
np1=np.random.rand(2,3)
np1

array([[0.56465099, 0.90153501, 0.38416043],
       [0.1992937 , 0.81988417, 0.1638315 ]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
ab=torch.randn(2,3)
ab

tensor([[-0.3735, -0.3019, -0.4175],
        [ 0.3266, -0.4740, -0.0195]])

In [ ]:
ab.dtype

torch.float32

In [ ]:
abc=torch.zeros(3,2,2)
abc

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
abcd=torch.tensor(np1)
abcd

tensor([[0.5647, 0.9015, 0.3842],
        [0.1993, 0.8199, 0.1638]], dtype=torch.float64)

In [ ]:
wt=torch.arange(10)
wt

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
wt=wt.reshape(2,5)
wt

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
op=torch.arange(15)
op

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
op=op.reshape(3,-1)
op

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
t1=torch.arange(15)
t1=t1.view(3,-1)
t1

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
t2=torch.arange(10)
t2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
t2[7]   #here the outpit is not value but the index or scale you can say

tensor(7)

In [ ]:
t2=t2.reshape(5,2)
t2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
t2[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
t2[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [ ]:
t6=torch.tensor([1,2,3,4])
t7=torch.tensor([5,6,7,8])


In [ ]:
add=t6+t7
add

tensor([ 6,  8, 10, 12])

In [ ]:
torch.add(t6,t7)

tensor([ 6,  8, 10, 12])

In [ ]:
sub=t7-t6
sub

tensor([4, 4, 4, 4])

In [ ]:
torch.sub(t7,t6)

tensor([4, 4, 4, 4])

In [ ]:
t6*t7

tensor([ 5, 12, 21, 32])

In [ ]:
torch.multiply(t6,t7)

tensor([ 5, 12, 21, 32])

In [ ]:
t7/t6

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
torch.divide(t7,t6)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
t7 % t6

tensor([0, 0, 1, 0])

In [ ]:
torch.remainder(t7,t6)

tensor([0, 0, 1, 0])

In [ ]:
torch.pow(t6,t7)

tensor([    1,    64,  2187, 65536])